---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: integration-service
  namespace: integration-service
spec:
  latestResourceSchemas:
  - md5-bdbd79111419cb45ed5f46c858d8ff96.integrationtestscenarios.appstudio.redhat.com
  permissionClaims:
  - group: tekton.dev
    identityHash: pipeline-service
    resource: pipelineruns
  - group: appstudio.redhat.com
    identityHash: application-api
    resource: applications
  - group: appstudio.redhat.com
    identityHash: application-api
    resource: components
  - group: appstudio.redhat.com
    identityHash: application-api
    resource: applicationsnapshots
  - group: appstudio.redhat.com
    identityHash: application-api
    resource: environments
  - group: appstudio.redhat.com
    identityHash: application-api
    resource: applicationsnapshotenvironmentbindings
  - group: appstudio.redhat.com
    identityHash: release-service
    resource: releases
  - group: appstudio.redhat.com
    identityHash: release-service
    resource: releaseplans
