apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: application-api
spec:
  reference:
    workspace:
      path: ${APPSTUDIO_SP_WORKSPACE}
      exportName: application-api
  permissionClaims:
  - group: ""
    resource: secrets
    state: Accepted
  - group: ""
    resource: namespaces
    state: Accepted
  - group: ""
    resource: configmaps
    state: Accepted
