apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: service-provider-integration
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: service-provider-integration
