kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: service-provider-integration
spec:
  to:
    kind: Service
    name: el-service-provider-integration
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None