apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spi-vault

resources:
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/vault/openshift?ref=13aff67f9ad6f5b583e5e8d952441bdd02739fa7
