kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kcp-syncer-kcp-stable-edit
  namespace: kcp-syncer-kcp-stable
subjects:
  - kind: User
    name: skabashnyuk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
