resources:
- https://github.com/redhat-appstudio/dora-metrics/deploy/base?ref=68814cca4f0d767b11cceb4f2c6ea0220ed8d449

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/redhat-appstudio/dora-metrics
    newName: quay.io/redhat-appstudio/dora-metrics
    newTag: 68814cca4f0d767b11cceb4f2c6ea0220ed8d449
