apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../appstudio

patches:
- patch: |-
    - op: replace
      path: /metadata/labels
      value:
        provided-by: infra-deployments
  target:
    kind: APIBinding
