resources:
- https://github.com/redhat-appstudio/jvm-build-service/deploy/kcp?ref=954c86b39a12820c7910c93b1e20b9b572232816

images:
- name: hacbs-jvm-operator
  newName: quay.io/redhat-appstudio/hacbs-jvm-controller
  newTag: 954c86b39a12820c7910c93b1e20b9b572232816

namespace: jvm-build-service

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- |-
  apiVersion: jvmbuildservice.io/v1alpha1
  kind: SystemConfig
  metadata:
    name: cluster
  $patch: delete
- |-
  apiVersion: apis.kcp.dev/v1alpha1
  kind: APIBinding
  metadata:
    name: jvmbuildservice-binding
  $patch: delete
- |-
  apiVersion: apis.kcp.dev/v1alpha1
  kind: APIExport
  metadata:
    name: jvmbuildservice
