---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: jvm-build-service
spec:
  reference:
    workspace:
      exportName: jvm-build-service
  permissionClaims:
  - group: ""
    resource: secrets
    state: Accepted
  - group: ""
    resource: serviceaccounts
    state: Accepted
  - group: ""
    resource: events
    state: Accepted
