kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-pdave
  namespace: pdave
subjects:
  - kind: User
    name: pdaverh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
