apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  cm-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  cm-reader
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
