---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authorization-in-cluster
$patch: delete
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kcp-syncer
$patch: delete
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-workload-in-cluster
$patch: delete
