---
apiVersion: v1
kind: Namespace
metadata:
  name: kcp-syncer-kcp-stable
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcp-syncer-appstudio-internal-209j7z8n
  namespace: kcp-syncer-kcp-stable
---
apiVersion: v1
kind: Secret
metadata:
  name: kcp-syncer-appstudio-internal-209j7z8n-token
  namespace: kcp-syncer-kcp-stable
  annotations:
    kubernetes.io/service-account.name: kcp-syncer-appstudio-internal-209j7z8n
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcp-syncer-appstudio-internal-209j7z8n
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - "create"
  - "list"
  - "watch"
  - "delete"
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  - services
  verbs:
  - "*"
- apiGroups:
  - "apps"
  resources:
  - deployments
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcp-syncer-appstudio-internal-209j7z8n
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcp-syncer-appstudio-internal-209j7z8n
subjects:
- kind: ServiceAccount
  name: kcp-syncer-appstudio-internal-209j7z8n
  namespace: kcp-syncer-kcp-stable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcp-syncer-appstudio-internal-209j7z8n
  namespace: kcp-syncer-kcp-stable
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kcp-syncer-appstudio-internal-209j7z8n
  template:
    metadata:
      labels:
        app: kcp-syncer-appstudio-internal-209j7z8n
    spec:
      containers:
      - name: kcp-syncer
        command:
        - /ko-app/syncer
        args:
        - --from-kubeconfig=/kcp/kubeconfig
        - --sync-target-name=appstudio-internal
        - --sync-target-uid=1d707902-e3c6-4085-96b6-25a2fa9c9aad
        - --from-cluster=root:redhat-appstudio-internal-compute
        - --api-import-poll-interval=1m0s
        - --resources=configmaps
        - --resources=deployments.apps
        - --resources=routes.route.openshift.io
        - --resources=secrets
        - --resources=serviceaccounts
        - --resources=services
        - --resources=statefulsets.apps
        - --qps=20
        - --burst=30
        image: ghcr.io/kcp-dev/kcp/syncer:v0.9.0
        imagePullPolicy: Always
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: kcp-config
          mountPath: /kcp/
          readOnly: true
      serviceAccountName: kcp-syncer-appstudio-internal-209j7z8n
      volumes:
        - name: kcp-config
          secret:
            secretName: kcp-syncer-appstudio-internal-209j7z8n
            optional: false
