kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-as-code-maintainers
  namespace: pipelines-as-code
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: sbose78
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: jduimovich
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: chmouel
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: Michkov
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-maintainer
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: build-templates-maintainers
  namespace: build-templates
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: sbose78
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: jduimovich
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: Michkov
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-maintainer
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-maintainers
  namespace: tekton-pipelines
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: sbose78
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: jduimovich
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: Michkov
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: goldmann
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-maintainer
