kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-registration-maintainer
rules:
  - verbs:
      - list
      - get
      - delete
      - update
      - patch
    apiGroups:
      - 'singapore.open-cluster-management.io'
    resources:
      - clusterregistrars
      - hubconfigs
      - registeredclusters
  - verbs:
      - create # allows addition of credentials only.
      - delete
      - list
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - '*' # needed till we figure out how to cleanup workspaces.
    apiGroups:
      - 'tekton.dev'
    resources:
      - 'pipelineruns'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-registration-maintainer-rolebinding
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: chrisahl
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: robinbobbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-registration-maintainer
