kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spi-service-ci-maintainers
  namespace: spi-system
subjects:
  - kind: User
    name: skabashnyuk
  - kind: User
    name: sbose78
  - kind: User
    name: Michkov
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-maintainer
