kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-gitops-service
  namespace: gitops
subjects:
  - kind: Group
    name: GitOps Service Team
  - kind: User
    name: sbose78
  - kind: User
    name: CathalOConnorRH
  - kind: User
    name: Michkov
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-gitops-service
  namespace: gitops-service-argocd
subjects:
  - kind: Group
    name: GitOps Service Team
  - kind: User
    name: sbose78
  - kind: User
    name: CathalOConnorRH
  - kind: User
    name: Michkov
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
