kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-integration
  namespace: integration-service
subjects:
  - kind: Group
    name: Test team
  - kind: Group
    name: Build team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
